apiVersion: v1
kind: Pod
spec:
  containers:
    # ruleid: run-as-non-root-unsafe-value
    - name: redis
      image: redis
      securityContext:
        runAsNonRoot: false
    # ok: run-as-non-root-unsafe-value
    - name: haproxy
      image: haproxy
      securityContext:
        runAsNonRoot: true
